import 'package:t_store/features/shop/models/banner_model.dart';
import 'package:t_store/features/shop/models/brand_category_model.dart';
import 'package:t_store/features/shop/models/brand_model.dart';
import 'package:t_store/features/shop/models/category_model.dart';
import 'package:t_store/features/shop/models/product_attribute_model.dart';
import 'package:t_store/features/shop/models/product_category_model.dart';
import 'package:t_store/features/shop/models/product_model.dart';
import 'package:t_store/features/shop/models/product_variation_model.dart';

import 'image_strings.dart';
import '../../routes/routes.dart';

class TDummyData {
  /// -- List of all banners
  static final List<BannerModel> banners = [
    BannerModel(
      imageUrl: TImages.promoBanner1,
      targetScreen: TRoutes.order,
      active: true,
    ),
    BannerModel(
      imageUrl: TImages.promoBanner2,
      targetScreen: TRoutes.favourites,
      active: true,
    ),
    BannerModel(
      imageUrl: TImages.promoBanner3,
      targetScreen: TRoutes.cart,
      active: true,
    ),
    BannerModel(
      imageUrl: TImages.banner1,
      targetScreen: TRoutes.order,
      active: false,
    ),
    BannerModel(
      imageUrl: TImages.banner2,
      targetScreen: TRoutes.order,
      active: false,
    ),
    BannerModel(
      imageUrl: TImages.banner3,
      targetScreen: TRoutes.order,
      active: false,
    ),
    BannerModel(
      imageUrl: TImages.banner4,
      targetScreen: TRoutes.order,
      active: false,
    ),
    BannerModel(
      imageUrl: TImages.banner5,
      targetScreen: TRoutes.order,
      active: false,
    ),
    BannerModel(
      imageUrl: TImages.banner6,
      targetScreen: TRoutes.order,
      active: false,
    ),
    BannerModel(
      imageUrl: TImages.banner8,
      targetScreen: TRoutes.order,
      active: false,
    ),
  ];

  /// -- List of all categories
  static final List<CategoryModel> categories = [
    CategoryModel(
        id: '1', name: 'Sports', image: TImages.sportIcon, isFeatured: true),
    CategoryModel(
        id: '2',
        name: 'Electronics',
        image: TImages.electronicsIcon,
        isFeatured: true),
    CategoryModel(
        id: '3', name: 'Clothes', image: TImages.clothIcon, isFeatured: true),
    CategoryModel(
        id: '4', name: 'Animals', image: TImages.animalIcon, isFeatured: true),
    CategoryModel(
        id: '5',
        name: 'Furniture',
        image: TImages.furnitureIcon,
        isFeatured: true),
    CategoryModel(
        id: '6', name: 'Shoes', image: TImages.shoeIcon, isFeatured: true),
    CategoryModel(
        id: '7',
        name: 'Cosmetics',
        image: TImages.cosmeticsIcon,
        isFeatured: true),
    CategoryModel(
        id: '8', name: 'Books', image: TImages.jeweleryIcon, isFeatured: true),

    // Sub Categories
    CategoryModel(
        id: '9',
        name: 'Sport Shoes',
        image: TImages.sportIcon,
        isFeatured: false,
        parentId: '1'),
    CategoryModel(
        id: '10',
        name: 'Track Suits',
        image: TImages.sportIcon,
        isFeatured: false,
        parentId: '1'),
    CategoryModel(
        id: '11',
        name: 'Sports Equipment',
        image: TImages.sportIcon,
        isFeatured: false,
        parentId: '1'),

    //furniture
    CategoryModel(
        id: '12',
        name: 'Bedroom furniture',
        image: TImages.furnitureIcon,
        isFeatured: false,
        parentId: '5'),
    CategoryModel(
        id: '13',
        name: 'Kitchen furniture',
        image: TImages.furnitureIcon,
        isFeatured: false,
        parentId: '5'),
    CategoryModel(
        id: '14',
        name: 'Office furniture',
        image: TImages.furnitureIcon,
        isFeatured: false,
        parentId: '5'),

    //electronics
    CategoryModel(
        id: '15',
        name: 'Laptop',
        image: TImages.electronicsIcon,
        isFeatured: false,
        parentId: '2'),
    CategoryModel(
        id: '16',
        name: 'Mobile',
        image: TImages.electronicsIcon,
        isFeatured: false,
        parentId: '2'),

    CategoryModel(
        id: '17',
        name: 'Shirts',
        image: TImages.clothIcon,
        isFeatured: false,
        parentId: '3'),
  ];

  static final List<BrandModel> brands = [
    BrandModel(
        id: '1',
        image: TImages.nikeLogo,
        name: 'Nike',
        productsCount: 256,
        isFeatured: true),
    BrandModel(
        id: '2',
        image: TImages.adidasLogo,
        name: 'Adidas',
        productsCount: 95,
        isFeatured: true),
    BrandModel(
        id: '8',
        image: TImages.kenwoodLogo,
        name: 'Kenwood',
        productsCount: 36,
        isFeatured: false),
    BrandModel(
        id: '9',
        image: TImages.ikeaLogo,
        name: 'Ikea',
        productsCount: 36,
        isFeatured: false),
    BrandModel(
        id: '5',
        image: TImages.appleLogo,
        name: 'Apple',
        productsCount: 16,
        isFeatured: true),
    BrandModel(
        id: '10',
        image: TImages.acerlogo,
        name: 'Acer',
        isFeatured: false,
        productsCount: 36),
    BrandModel(
        id: '3',
        image: TImages.jordanLogo,
        name: 'Jordan',
        isFeatured: true,
        productsCount: 35),
    BrandModel(
        id: '4',
        image: TImages.pumaLogo,
        name: 'Puma',
        isFeatured: true,
        productsCount: 35),
    BrandModel(
        id: '6',
        image: TImages.zaraLogo,
        name: 'ZARA',
        isFeatured: true,
        productsCount: 35),
    BrandModel(
        id: '7',
        image: TImages.electronicsIcon,
        name: 'Samsung',
        isFeatured: false,
        productsCount: 35),
  ];

  static final List<BrandCategoryModel> brandCategory = [
    BrandCategoryModel(brandId: '1', categoryId: '1'),
    BrandCategoryModel(brandId: '1', categoryId: '8'),
    BrandCategoryModel(brandId: '1', categoryId: '9'),
    BrandCategoryModel(brandId: '1', categoryId: '10'),
    BrandCategoryModel(brandId: '2', categoryId: '1'),
    BrandCategoryModel(brandId: '2', categoryId: '8'),
    BrandCategoryModel(brandId: '2', categoryId: '9'),
    BrandCategoryModel(brandId: '2', categoryId: '10'),
    BrandCategoryModel(brandId: '3', categoryId: '1'),
    BrandCategoryModel(brandId: '3', categoryId: '8'),
    BrandCategoryModel(brandId: '3', categoryId: '9'),
    BrandCategoryModel(brandId: '3', categoryId: '10'),
    BrandCategoryModel(brandId: '4', categoryId: '1'),
    BrandCategoryModel(brandId: '4', categoryId: '8'),
    BrandCategoryModel(brandId: '4', categoryId: '9'),
    BrandCategoryModel(brandId: '4', categoryId: '10'),
    BrandCategoryModel(brandId: '5', categoryId: '15'),
    BrandCategoryModel(brandId: '5', categoryId: '2'),
    BrandCategoryModel(brandId: '10', categoryId: '2'),
    BrandCategoryModel(brandId: '10', categoryId: '14'),
    BrandCategoryModel(brandId: '6', categoryId: '3'),
    BrandCategoryModel(brandId: '6', categoryId: '16'),
    BrandCategoryModel(brandId: '7', categoryId: '2'),
    BrandCategoryModel(brandId: '8', categoryId: '5'),
    BrandCategoryModel(brandId: '8', categoryId: '11'),
    BrandCategoryModel(brandId: '8', categoryId: '12'),
    BrandCategoryModel(brandId: '8', categoryId: '13'),
    BrandCategoryModel(brandId: '9', categoryId: '5'),
    BrandCategoryModel(brandId: '9', categoryId: '11'),
    BrandCategoryModel(brandId: '9', categoryId: '12'),
    BrandCategoryModel(brandId: '9', categoryId: '13'),
  ];

  static final List<ProductCategoryModel> productCategories = [
    ProductCategoryModel(productId: '001', categoryId: '1'),
    ProductCategoryModel(productId: '001', categoryId: '8'),
    ProductCategoryModel(productId: '004', categoryId: '3'),
    ProductCategoryModel(productId: '002', categoryId: '3'),
    ProductCategoryModel(productId: '002', categoryId: '16'),
    ProductCategoryModel(productId: '003', categoryId: '3'),
    ProductCategoryModel(productId: '005', categoryId: '1'),
    ProductCategoryModel(productId: '005', categoryId: '8'),
    ProductCategoryModel(productId: '040', categoryId: '2'),
    ProductCategoryModel(productId: '040', categoryId: '15'),
    ProductCategoryModel(productId: '006', categoryId: '2'),
    ProductCategoryModel(productId: '007', categoryId: '4'),
    ProductCategoryModel(productId: '009', categoryId: '1'),
    ProductCategoryModel(productId: '009', categoryId: '8'),
    ProductCategoryModel(productId: '010', categoryId: '1'),
    ProductCategoryModel(productId: '010', categoryId: '8'),
    ProductCategoryModel(productId: '011', categoryId: '1'),
    ProductCategoryModel(productId: '011', categoryId: '8'),
    ProductCategoryModel(productId: '012', categoryId: '1'),
    ProductCategoryModel(productId: '012', categoryId: '8'),
    ProductCategoryModel(productId: '013', categoryId: '8'),
    ProductCategoryModel(productId: '014', categoryId: '1'),
    ProductCategoryModel(productId: '014', categoryId: '9'),
    ProductCategoryModel(productId: '015', categoryId: '1'),
    ProductCategoryModel(productId: '015', categoryId: '9'),
    ProductCategoryModel(productId: '016', categoryId: '1'),
    ProductCategoryModel(productId: '016', categoryId: '9'),
    ProductCategoryModel(productId: '017', categoryId: '1'),
    ProductCategoryModel(productId: '017', categoryId: '9'),
    ProductCategoryModel(productId: '018', categoryId: '1'),
    ProductCategoryModel(productId: '018', categoryId: '10'),
    ProductCategoryModel(productId: '019', categoryId: '1'),
    ProductCategoryModel(productId: '019', categoryId: '10'),
    ProductCategoryModel(productId: '020', categoryId: '1'),
    ProductCategoryModel(productId: '020', categoryId: '10'),
    ProductCategoryModel(productId: '021', categoryId: '1'),
    ProductCategoryModel(productId: '021', categoryId: '10'),
    ProductCategoryModel(productId: '022', categoryId: '5'),
    ProductCategoryModel(productId: '022', categoryId: '11'),
    ProductCategoryModel(productId: '023', categoryId: '5'),
    ProductCategoryModel(productId: '023', categoryId: '11'),
    ProductCategoryModel(productId: '024', categoryId: '5'),
    ProductCategoryModel(productId: '024', categoryId: '11'),
    ProductCategoryModel(productId: '025', categoryId: '5'),
    ProductCategoryModel(productId: '025', categoryId: '11'),
    ProductCategoryModel(productId: '026', categoryId: '5'),
    ProductCategoryModel(productId: '026', categoryId: '12'),
    ProductCategoryModel(productId: '027', categoryId: '5'),
    ProductCategoryModel(productId: '027', categoryId: '12'),
    ProductCategoryModel(productId: '028', categoryId: '5'),
    ProductCategoryModel(productId: '028', categoryId: '12'),
    ProductCategoryModel(productId: '029', categoryId: '5'),
    ProductCategoryModel(productId: '029', categoryId: '13'),
    ProductCategoryModel(productId: '030', categoryId: '5'),
    ProductCategoryModel(productId: '030', categoryId: '13'),
    ProductCategoryModel(productId: '031', categoryId: '5'),
    ProductCategoryModel(productId: '031', categoryId: '13'),
    ProductCategoryModel(productId: '032', categoryId: '5'),
    ProductCategoryModel(productId: '032', categoryId: '13'),
    ProductCategoryModel(productId: '033', categoryId: '2'),
    ProductCategoryModel(productId: '033', categoryId: '14'),
    ProductCategoryModel(productId: '034', categoryId: '2'),
    ProductCategoryModel(productId: '034', categoryId: '14'),
    ProductCategoryModel(productId: '035', categoryId: '2'),
    ProductCategoryModel(productId: '035', categoryId: '14'),
    ProductCategoryModel(productId: '036', categoryId: '2'),
    ProductCategoryModel(productId: '036', categoryId: '14'),
    ProductCategoryModel(productId: '037', categoryId: '2'),
    ProductCategoryModel(productId: '037', categoryId: '15'),
    ProductCategoryModel(productId: '038', categoryId: '2'),
    ProductCategoryModel(productId: '038', categoryId: '15'),
    ProductCategoryModel(productId: '039', categoryId: '2'),
    ProductCategoryModel(productId: '039', categoryId: '15'),
    ProductCategoryModel(productId: '008', categoryId: '2'),
  ];

  static final List<ProductModel> products = [
    ProductModel(
      id: '001',
      title: 'Green Nike sports shoe',
      stock: 15,
      price: 135,
      isFeatured: true,
      thumbnail: TImages.productImage1,
      description: 'Green Nike sports shoe',
      brand: BrandModel(
          id: '1',
          image: TImages.nikeLogo,
          name: 'Nike',
          productsCount: 265,
          isFeatured: true),
      images: [
        TImages.productImage1,
        TImages.productImage23,
        TImages.productImage21,
        TImages.productImage9,
      ],
      salePrice: 30,
      sku: 'ABR4568',
      categoryId: '1',
      productAttributes: [
        ProductAttributeModel(name: 'Color', values: ['Green', 'Black', 'Red']),
        ProductAttributeModel(
            name: 'Size', values: ['EU 30', 'EU 32', 'EU 34']),
      ],
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 34,
          price: 134,
          salePrice: 122.6,
          image: TImages.productImage1,
          description: 'This is a product description for Green',
          attributesValues: {'Color': 'Green', 'Size': 'EU 34'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 15,
          price: 135,
          image: TImages.productImage23,
          attributesValues: {'Color': 'Black', 'Size': 'EU 32'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 0,
          price: 234,
          image: TImages.productImage1,
          attributesValues: {'Color': 'Black', 'Size': 'EU 32'},
        ),
        ProductVariationModel(
          id: '4',
          stock: 222,
          price: 232,
          image: TImages.productImage1,
          attributesValues: {'Color': 'Green', 'Size': 'EU 32'},
        ),
        ProductVariationModel(
          id: '5',
          stock: 0,
          price: 334,
          image: TImages.productImage1,
          attributesValues: {'Color': 'Red', 'Size': 'EU 34'},
        ),
      ],
      productType: 'ProductType.variable',
    ),
    ProductModel(
      id: '002',
      title: 'Blue T-shirt for all ages',
      stock: 15,
      price: 35,
      isFeatured: true,
      thumbnail: TImages.productImage69,
      description:
          'This is a Product Description for Blue Nike Sleeve less vest. There are more things that can be added but I am just practicing and nothing else.',
      brand: BrandModel(id: '6', image: TImages.zaraLogo, name: 'ZARA'),
      images: [
        TImages.productImage68,
        TImages.productImage69,
        TImages.productImage5,
      ],
      salePrice: 30,
      sku: 'ABR4568',
      categoryId: '16',
      productAttributes: [
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
        ProductAttributeModel(name: 'Size', values: ['EU 32', 'EU 34']),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '003',
      title: 'Leather brown Jacket',
      stock: 15,
      price: 38000,
      isFeatured: false,
      thumbnail: TImages.productImage64,
      description:
          'This is a Product Description for Leather brown Jacket. There are more things that can be added but I am just practicing and nothing else.',
      brand: BrandModel(id: '6', image: TImages.zaraLogo, name: 'ZARA'),
      images: [
        TImages.productImage64,
        TImages.productImage65,
        TImages.productImage66,
        TImages.productImage67,
      ],
      salePrice: 30,
      sku: 'ABR4568',
      categoryId: '16',
      productAttributes: [
        ProductAttributeModel(name: 'Color', values: ['Green', 'Red', 'Blue']),
        ProductAttributeModel(name: 'Size', values: ['EU 32', 'EU 34']),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '004',
      title: '4 Color collar T-shirt dry fit',
      stock: 15,
      price: 135,
      isFeatured: false,
      thumbnail: TImages.productImage70,
      description:
          'This is a Product Description for 4 Color collar T-shirt dry fit. There are more things that can be added but I am just practicing and nothing else.',
      brand: BrandModel(id: '6', image: TImages.zaraLogo, name: 'ZARA'),
      images: [
        TImages.productImage60,
        TImages.productImage61,
        TImages.productImage62,
        TImages.productImage63,
      ],
      salePrice: 30,
      sku: 'ABR4568',
      categoryId: '16',
      productAttributes: [
        ProductAttributeModel(
            name: 'Color', values: ['Red', 'Yellow', 'Green']),
        ProductAttributeModel(
            name: 'Size', values: ['EU 30', 'EU 32', 'EU 34']),
      ],
      productVariations: [
        ProductVariationModel(
          id: '1',
          stock: 34,
          price: 134,
          salePrice: 122.6,
          image: TImages.productImage60,
          description:
              'This is a Product Description for 4 Color collar T-shirt dry fit.',
          attributesValues: {'Color': 'Green', 'Size': 'EU 34'},
        ),
        ProductVariationModel(
          id: '2',
          stock: 15,
          price: 132,
          image: TImages.productImage60,
          attributesValues: {'Color': 'Yellow', 'Size': 'EU 32'},
        ),
        ProductVariationModel(
          id: '3',
          stock: 0,
          price: 234,
          image: TImages.productImage61,
          attributesValues: {'Color': 'Yellow', 'Size': 'EU 32'},
        ),
        ProductVariationModel(
          id: '4',
          stock: 222,
          price: 232,
          image: TImages.productImage61,
          attributesValues: {'Color': 'Red', 'Size': 'EU 34'},
        ),
        ProductVariationModel(
          id: '5',
          stock: 0,
          price: 334,
          image: TImages.productImage62,
          attributesValues: {'Color': 'Green', 'Size': 'EU 34'},
        ),
        ProductVariationModel(
          id: '6',
          stock: 11,
          price: 332,
          image: TImages.productImage62,
          attributesValues: {'Color': 'Green', 'Size': 'EU 30'},
        ),
        ProductVariationModel(
          id: '7',
          stock: 0,
          price: 334,
          image: TImages.productImage63,
          attributesValues: {'Color': 'Blue', 'Size': 'EU 30'},
        ),
        ProductVariationModel(
          id: '8',
          stock: 11,
          price: 332,
          image: TImages.productImage63,
          attributesValues: {'Color': 'Blue', 'Size': 'EU 34'},
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '010',
      title: 'Apple MacBook Pro',
      stock: 10,
      price: 1999,
      isFeatured: true,
      thumbnail: TImages.productImage23,
      description: 'Apple MacBook Pro with Retina Display',
      brand: BrandModel(
        id: '11',
        image: TImages.appleLogo,
        name: 'Apple',
      ),
      images: [
        TImages.productImage23,
        TImages.productImage24,
        TImages.productImage25,
        TImages.productImage26,
      ],
      salePrice: 1899,
      sku: 'ABR4568',
      categoryId: '2',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['Silver', 'Space Gray'],
        ),
        ProductAttributeModel(
          name: 'Size',
          values: ['13-inch', '15-inch'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '011',
      title: 'Sony PlayStation 5',
      stock: 5,
      price: 499,
      isFeatured: true,
      thumbnail: TImages.productImage27,
      description: 'Sony PlayStation 5 Gaming Console',
      brand: BrandModel(
        id: '12',
        image: TImages.appleLogo,
        name: 'Sony',
      ),
      images: [
        TImages.productImage27,
        TImages.productImage28,
        TImages.productImage29,
        TImages.productImage30,
      ],
      salePrice: 449,
      sku: 'ABR4568',
      categoryId: '3',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['White', 'Black'],
        ),
        ProductAttributeModel(
          name: 'Storage',
          values: ['500GB', '1TB'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '012',
      title: 'Samsung 4K Smart TV',
      stock: 8,
      price: 799,
      isFeatured: true,
      thumbnail: TImages.productImage31,
      description: 'Samsung 4K Ultra HD Smart TV',
      brand: BrandModel(
        id: '7',
        image: TImages.electronicsIcon,
        name: 'Samsung',
      ),
      images: [
        TImages.productImage31,
        TImages.productImage32,
        TImages.productImage33,
        TImages.productImage34,
      ],
      salePrice: 749,
      sku: 'ABR4568',
      categoryId: '5',
      productAttributes: [
        ProductAttributeModel(
          name: 'Screen Size',
          values: ['55-inch', '65-inch'],
        ),
        ProductAttributeModel(
          name: 'Resolution',
          values: ['4K', '8K'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '013',
      title: 'Canon EOS Rebel T7',
      stock: 12,
      price: 499,
      isFeatured: true,
      thumbnail: TImages.productImage35,
      description: 'Canon EOS Rebel T7 DSLR Camera',
      brand: BrandModel(
        id: '13',
        image: TImages.electronicsIcon,
        name: 'Canon',
      ),
      images: [
        TImages.productImage35,
        TImages.productImage36,
        TImages.productImage37,
        TImages.productImage38,
      ],
      salePrice: 449,
      sku: 'ABR4568',
      categoryId: '6',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['Black'],
        ),
        ProductAttributeModel(
          name: 'Lens',
          values: ['18-55mm', '75-300mm'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '014',
      title: 'Fitbit Versa 3',
      stock: 20,
      price: 229,
      isFeatured: true,
      thumbnail: TImages.productImage39,
      description: 'Fitbit Versa 3 Smartwatch',
      brand: BrandModel(
        id: '14',
        image: TImages.ikeaLogo,
        name: 'Fitbit',
      ),
      images: [
        TImages.productImage39,
        TImages.productImage40,
        TImages.productImage41,
        TImages.productImage42,
      ],
      salePrice: 199,
      sku: 'ABR4568',
      categoryId: '7',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['Black', 'White', 'Pink'],
        ),
        ProductAttributeModel(
          name: 'Size',
          values: ['Small', 'Large'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '015',
      title: 'Amazon Echo Dot',
      stock: 15,
      price: 49,
      isFeatured: true,
      thumbnail: TImages.productImage43,
      description: 'Amazon Echo Dot Smart Speaker',
      brand: BrandModel(
        id: '15',
        image: TImages.appleLogo,
        name: 'Amazon',
      ),
      images: [
        TImages.productImage43,
        TImages.productImage44,
        TImages.productImage45,
        TImages.productImage46,
      ],
      salePrice: 39,
      sku: 'ABR4568',
      categoryId: '9',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['Charcoal', 'Sandstone'],
        ),
        ProductAttributeModel(
          name: 'Generation',
          values: ['3rd Gen', '4th Gen'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '016',
      title: 'Nintendo Switch',
      stock: 10,
      price: 299,
      isFeatured: true,
      thumbnail: TImages.productImage47,
      description: 'Nintendo Switch Gaming Console',
      brand: BrandModel(
        id: '16',
        image: TImages.jordanLogo,
        name: 'Nintendo',
      ),
      images: [
        TImages.productImage47,
        TImages.productImage48,
        TImages.productImage49,
        TImages.productImage50,
      ],
      salePrice: 279,
      sku: 'ABR4568',
      categoryId: '3',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['Neon Blue/Red', 'Gray'],
        ),
        ProductAttributeModel(
          name: 'Storage',
          values: ['32GB', '64GB'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '017',
      title: 'LG OLED TV',
      stock: 8,
      price: 1999,
      isFeatured: true,
      thumbnail: TImages.productImage51,
      description: 'LG OLED 4K Ultra HD Smart TV',
      brand: BrandModel(
        id: '17',
        image: TImages.adidasLogo,
        name: 'LG',
      ),
      images: [
        TImages.productImage51,
        TImages.productImage52,
        TImages.productImage53,
        TImages.productImage54,
      ],
      salePrice: 1899,
      sku: 'ABR4568',
      categoryId: '5',
      productAttributes: [
        ProductAttributeModel(
          name: 'Screen Size',
          values: ['55-inch', '65-inch'],
        ),
        ProductAttributeModel(
          name: 'Resolution',
          values: ['4K', '8K'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '018',
      title: 'Sony Alpha a7 III',
      stock: 12,
      price: 1999,
      isFeatured: true,
      thumbnail: TImages.productImage55,
      description: 'Sony Alpha a7 III Mirrorless Camera',
      brand: BrandModel(
        id: '12',
        image: TImages.darkAppLogo,
        name: 'Sony',
      ),
      images: [
        TImages.productImage55,
        TImages.productImage56,
        TImages.productImage57,
        TImages.productImage58,
      ],
      salePrice: 1899,
      sku: 'ABR4568',
      categoryId: '6',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['Black'],
        ),
        ProductAttributeModel(
          name: 'Lens',
          values: ['24-70mm', '70-200mm'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '019',
      title: 'Bose QuietComfort 35 II',
      stock: 20,
      price: 299,
      isFeatured: true,
      thumbnail: TImages.productImage59,
      description: 'Bose QuietComfort 35 II Wireless Headphones',
      brand: BrandModel(
        id: '18',
        image: TImages.kenwoodLogo,
        name: 'Bose',
      ),
      images: [
        TImages.productImage59,
        TImages.productImage60,
        TImages.productImage61,
        TImages.productImage62,
      ],
      salePrice: 279,
      sku: 'ABR4568',
      categoryId: '7',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['Black', 'Silver'],
        ),
        ProductAttributeModel(
          name: 'Style',
          values: ['Over-Ear', 'On-Ear'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '020',
      title: 'Amazon Fire TV Stick',
      stock: 15,
      price: 39,
      isFeatured: true,
      thumbnail: TImages.productImage63,
      description: 'Amazon Fire TV Stick Streaming Media Player',
      brand: BrandModel(
        id: '15',
        image: TImages.appleLogo,
        name: 'Amazon',
      ),
      images: [
        TImages.productImage63,
        TImages.productImage64,
        TImages.productImage65,
        TImages.productImage66,
      ],
      salePrice: 29,
      sku: 'ABR4568',
      categoryId: '9',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['Black'],
        ),
        ProductAttributeModel(
          name: 'Generation',
          values: ['2nd Gen', '3rd Gen'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '021',
      title: 'Xbox Series X',
      stock: 10,
      price: 499,
      isFeatured: true,
      thumbnail: TImages.productImage67,
      description: 'Xbox Series X Gaming Console',
      brand: BrandModel(
        id: '19',
        image: TImages.darkAppLogo,
        name: 'Microsoft',
      ),
      images: [
        TImages.productImage67,
        TImages.productImage68,
        TImages.productImage69,
        TImages.productImage70,
      ],
      salePrice: 449,
      sku: 'ABR4568',
      categoryId: '3',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['Black'],
        ),
        ProductAttributeModel(
          name: 'Storage',
          values: ['1TB'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '022',
      title: 'Samsung Galaxy Watch',
      stock: 8,
      price: 349,
      isFeatured: true,
      thumbnail: TImages.productImage71,
      description: 'Samsung Galaxy Watch Active 2',
      brand: BrandModel(
        id: '7',
        image: TImages.electronicsIcon,
        name: 'Samsung',
      ),
      images: [
        TImages.productImage71,
        TImages.productImage72,
        TImages.productImage73,
        TImages.productImage74,
      ],
      salePrice: 329,
      sku: 'ABR4568',
      categoryId: '7',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['Black', 'Silver'],
        ),
        ProductAttributeModel(
          name: 'Size',
          values: ['40mm', '44mm'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '023',
      title: 'DJI Mavic Air 2',
      stock: 12,
      price: 799,
      isFeatured: true,
      thumbnail: TImages.productImage75,
      description: 'DJI Mavic Air 2 Drone',
      brand: BrandModel(
        id: '20',
        image: TImages.electronicsIcon,
        name: 'DJI',
      ),
      images: [
        TImages.productImage75,
        TImages.productImage76,
        TImages.productImage77,
        TImages.productImage32,
      ],
      salePrice: 749,
      sku: 'ABR4568',
      categoryId: '6',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['Gray'],
        ),
        ProductAttributeModel(
          name: 'Battery Life',
          values: ['30 minutes', '45 minutes'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '024',
      title: 'Garmin Forerunner 245',
      stock: 20,
      price: 299,
      isFeatured: true,
      thumbnail: TImages.productImage32,
      description: 'Garmin Forerunner 245 GPS Running Smartwatch',
      brand: BrandModel(
        id: '21',
        image: TImages.ikeaLogo,
        name: 'Garmin',
      ),
      images: [
        TImages.productImage32,
        TImages.productImage33,
        TImages.productImage34,
        TImages.productImage35,
      ],
      salePrice: 279,
      sku: 'ABR4568',
      categoryId: '7',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['Black', 'Aqua'],
        ),
        ProductAttributeModel(
          name: 'Size',
          values: ['Small', 'Large'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '025',
      title: 'Roku Streaming Stick+',
      stock: 15,
      price: 49,
      isFeatured: true,
      thumbnail: TImages.productImage50,
      description: 'Roku Streaming Stick+ HD/4K/HDR Streaming Media Player',
      brand: BrandModel(
        id: '22',
        image: TImages.ikeaLogo,
        name: 'Roku',
      ),
      images: [
        TImages.productImage50,
        TImages.productImage51,
        TImages.productImage52,
        TImages.productImage53,
      ],
      salePrice: 39,
      sku: 'ABR4568',
      categoryId: '9',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['Black'],
        ),
        ProductAttributeModel(
          name: 'Generation',
          values: ['2nd Gen', '3rd Gen'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '026',
      title: 'PlayStation VR',
      stock: 10,
      price: 299,
      isFeatured: true,
      thumbnail: TImages.productImage54,
      description: 'PlayStation VR Gaming Headset',
      brand: BrandModel(
        id: '12',
        image: TImages.electronicsIcon,
        name: 'Sony',
      ),
      images: [
        TImages.productImage54,
        TImages.productImage55,
        TImages.productImage56,
        TImages.productImage57,
      ],
      salePrice: 279,
      sku: 'ABR4568',
      categoryId: '3',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['Black'],
        ),
        ProductAttributeModel(
          name: 'Version',
          values: ['CUH-ZVR2', 'CUH-ZVR1'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '027',
      title: 'Samsung Galaxy Tab S7',
      stock: 8,
      price: 649,
      isFeatured: true,
      thumbnail: TImages.productImage70,
      description: 'Samsung Galaxy Tab S7 Tablet',
      brand: BrandModel(
        id: '7',
        image: TImages.electronicsIcon,
        name: 'Samsung',
      ),
      images: [
        TImages.productImage70,
        TImages.productImage71,
        TImages.productImage72,
        TImages.productImage73,
      ],
      salePrice: 599,
      sku: 'ABR4568',
      categoryId: '2',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['Mystic Black', 'Mystic Bronze'],
        ),
        ProductAttributeModel(
          name: 'Storage',
          values: ['128GB', '256GB'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '028',
      title: 'Nikon D3500',
      stock: 12,
      price: 499,
      isFeatured: true,
      thumbnail: TImages.productImage9,
      description: 'Nikon D3500 DSLR Camera',
      brand: BrandModel(
        id: '23',
        image: TImages.ikeaLogo,
        name: 'Nikon',
      ),
      images: [
        TImages.productImage9,
        TImages.productImage10,
        TImages.productImage11,
        TImages.productImage12,
      ],
      salePrice: 449,
      sku: 'ABR4568',
      categoryId: '6',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['Black'],
        ),
        ProductAttributeModel(
          name: 'Lens',
          values: ['18-55mm', '70-300mm'],
        ),
      ],
      productType: 'ProductType.single',
    ),
    ProductModel(
      id: '029',
      title: 'JBL Flip 5',
      stock: 20,
      price: 119,
      isFeatured: true,
      thumbnail: TImages.productImage30,
      description: 'JBL Flip 5 Portable Bluetooth Speaker',
      brand: BrandModel(
        id: '24',
        image: TImages.appleLogo,
        name: 'JBL',
      ),
      images: [
        TImages.productImage30,
        TImages.productImage31,
        TImages.productImage32,
        TImages.productImage33,
      ],
      salePrice: 99,
      sku: 'ABR4568',
      categoryId: '7',
      productAttributes: [
        ProductAttributeModel(
          name: 'Color',
          values: ['Black', 'Blue', 'Red'],
        ),
        ProductAttributeModel(
          name: 'Style',
          values: ['Flip 5'],
        ),
      ],
      productType: 'ProductType.single',
    ),
  ];
}
