name: t_store
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


#----------------- PACKAGES -----------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  image_picker: ^1.1.1
  url_launcher: ^6.1.12
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.3.13
  smooth_page_indicator: ^1.1.0

  # icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core: ^2.31.1
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.6
  cached_network_image: ^3.3.1



#----------------- ./ PACKAGES END -----------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  
  #----------------- LOCAL ASSETS -----------------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/icons/brands/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/reviews/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #----------------- LOCAL FONTS -----------------#
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 800