// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMjbR8TiyJ4ii79hzJbThKSIGuSXlcjSM',
    appId: '1:90209894923:web:20889051f1975859bffd0e',
    messagingSenderId: '90209894923',
    projectId: 'ecommerceapp-98a65',
    authDomain: 'ecommerceapp-98a65.firebaseapp.com',
    storageBucket: 'ecommerceapp-98a65.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUw3nXBhrBfjUQTdq9QFG33nVz64BYbqY',
    appId: '1:90209894923:android:1b8e8d4cb45414d0bffd0e',
    messagingSenderId: '90209894923',
    projectId: 'ecommerceapp-98a65',
    storageBucket: 'ecommerceapp-98a65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu47AqvKiXlYYRgDG-CuMMdRKekT9IJU8',
    appId: '1:90209894923:ios:17ee2f41aa104a8abffd0e',
    messagingSenderId: '90209894923',
    projectId: 'ecommerceapp-98a65',
    storageBucket: 'ecommerceapp-98a65.appspot.com',
    androidClientId: '90209894923-ka401jv6fph7f96vicodhpn704kkdd4u.apps.googleusercontent.com',
    iosClientId: '90209894923-fkhcfibkc9namtubhi0og3fsshcid8er.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}